export const ERROR_CODES = {
  USER_ALREADY_EXISTS: 1001, // ← UserErrorCase.USER_ALREADY_EXISTS의 errorCode로 수정
  EMAIL_NOT_ALLOWED: 3002, // AuthErrorCase.EMAIL_NOT_ALLOWED
  EMAIL_AUTH_ALREADY_VERIFIED: 2103, // AuthErrorCase.EMAIL_AUTH_ALREADY_VERIFIED
  EMAIL_AUTH_ALREADY_SENT: 2105, // AuthErrorCase.EMAIL_AUTH_ALREADY_SENT
} as const;
